### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by atc0005** [dasrick/go-teams-notify#23]
All,

When I was granted collaborator status in this project, it was understood that my changes to this project were to be made under supervision (which is fine, I was new to the project). That worked well with an active maintainer, but I have been unsuccessful in reaching @dasrick through a variety of means for some time. I can only conclude at this point that he is unavailable to continue further development of this project.

Because of that and due to the additional development that I've done on the codebase since he and I last spoke, I've decided to maintain my own fork of this project for the foreseeable future. Based on PRs and activity from other forks, I'm not alone in this decision.

See https://github.com/dasrick/go-teams-notify/network/members for a list of forks that have moved forward with further development.

For my part, I hope to see this project resume development at some future point and I will happily submit local fork changes for review and potential inclusion here.

**Comment by dasrick** [comment]
This project is no longer being actively developed or maintained. Please use the successor.

https://github.com/atc0005/go-teams-notify

THX to @atc0005
