### ISSUE TITLE
Checks invalid for custom URLs

### ISSUE THREAD

**Issue by ialbors** [dasrick/go-teams-notify#24]
This check:

https://github.com/dasrick/go-teams-notify/blob/dbc00d6e76ee362c8e35f6dc7ec47fb81ed7146f/send.go#L81

doesn't work for "custom enterprise installations" (?)

Some enterprise installations have a custom url, like:

enterprisejohndoeinc.webhook.office.com/....

**Comment by atc0005** [comment]
@ialbors 

https://github.com/atc0005/go-teams-notify/releases/tag/v2.4.2 should do what you're looking for. You can also disable all validation if you wish:

https://github.com/atc0005/go-teams-notify/blob/master/README.md#example-disable-webhook-url-prefix-validation

See also #23.

**Comment by dasrick** [comment]
This project is no longer being actively developed or maintained. Please use the successor.

https://github.com/atc0005/go-teams-notify

THX to @atc0005
