### ISSUE TITLE
Webhook URL validation: allow outlook.office365.com FQDN?

### ISSUE THREAD

**Issue by atc0005** [dasrick/go-teams-notify#3]
Hi,

First of all, thanks for providing this package. It allowed me to get up and going pretty quickly with a CLI app some months back in order to send notifications from shell scripts and Nagios to Teams.

I'm now working on fixing some validation problems with the CLI app and in the process I found that Microsoft uses this as their example webhook URL in their [documentation](https://docs.microsoft.com/en-us/outlook/actionable-messages/send-via-connectors#get-a-connector-webhook-url-for-your-inbox):

https://outlook.office365.com/webhook/a1269812-6d10-44b1-abc5-b84f93580ba0@9e7b80c7-d1eb-4b52-8582-76f921e416d9/IncomingWebhook/3fdd6767bae44ac58e5995547d66a4e4/f332c8d9-3397-4ac5-957b-b8e3fc465a8c

My Google-Fu is weak, as I've been unable to learn (yet?) whether the office365.com domain is deprecated in favor of office.com, but when testing I found that sending a POST request to webhook URLs based on either FQDN result in the message going to the desired Teams channel.

A long story short, what do you think of updating the validation function to accept either FQDN?

https://github.com/dasrick/go-teams-notify/blob/feea812b67f873b4959ec21f2f2c5265126e13e2/send.go#L78-L91

On that note, would it fit within your package design to expose that validation function for use by apps that use your package?

**Comment by atc0005** [comment]
I pushed up a branch to my fork to illustrate potential changes to `isValidWebhookURL()`. If you're interested, I can go ahead and submit as a Pull Request.

**Comment by dasrick** [comment]
Yes, please submit it as Pull Request.
As long as this is a valid FQDN for MS Teams, it should be part of this package. THX

**Comment by atc0005** [comment]
Working on this now and hope to have one submitted soon.

**Comment by atc0005** [comment]
> Working on this now and hope to have one submitted soon.

@dasrick Done.

Some potential, further changes related to this issue:

- `isValidWebhookURL` function
  - expose  for use by importing codebase
- webhook URL prefix strings
  - replace with constants
  - expose for use by importing codebase

If interested, I can submit a separate PR for those changes (or merge with #5 if that is preferred).
