### ISSUE TITLE
Is the Gopkg.lock file is out of date?

### ISSUE THREAD

**Issue by atc0005** [dasrick/go-teams-notify#7]
I've not learned much about Dep, but when researching how to [convert from Dep to Go Modules](https://stackoverflow.com/a/55664631) I found that v.1.1.1 of dasrick/go-teams-notify was brought in.

Looking at Gopkg.lock I see v1.1.1 defined:

https://github.com/dasrick/go-teams-notify/blob/97487a69edb5826fa9aca369fc12bbc6605294f6/Gopkg.lock#L4-L10

Not sure of your plans to convert from Dep to Go modules, but I'm guessing that Dep users would be impacted by the explicit v1.1.1 version (instead of the newer v1.3.0 release).

**Comment by dasrick** [comment]
1. i think, you are right with the version inside of `Gopkg.lock` ... needs to be updated
2. i planned to switch to go mod ... but in this case i would release a new major version and would not touch the "old" gopkg branch anymore ...

... but now there is someone who can help me to tackle this funny problem ...

thoughts for v2:
* use `go mod` instead of `dep`
* switch from golint to `golangci-lint`
* implement your idea of extended msgCard type
* maybe some improvements in README
* ...

What’s  do you think about it?

**Comment by atc0005** [comment]
All bullet points make sense to me, I don't know enough to say whether the switch between Dep and Go module is enough to force a v2 jump, but it is probably worth playing it safe and avoiding any potential issues from such a switch.

For my own CI runs (using GitHub Actions Workflows), I am using both `golint` and `golangci-lint`, but at this point it is probably overkill. I originally enabled both to see if `golint` happened to catch any issues that `golangci-lint` did not, but I've not seen anything from `golint` that `golangci-lint` didn't catch.

**Comment by atc0005** [comment]
> 2\. i planned to switch to go mod ... but in this case i would release a new major version and would not touch the "old" gopkg branch anymore ...

For now, do you consider `master` frozen or are you still accepting PRs against it? I noticed that in #5 I missed a doc comment on line 36 that I should have pruned or updated:

https://github.com/dasrick/go-teams-notify/blob/97487a69edb5826fa9aca369fc12bbc6605294f6/send.go#L34-L36

It's not functionally affecting anything, but when looking over the code today it stuck out and I figured I'd ask.

**Comment by dasrick** [comment]
The branch `master ` is not frozen.
I case of exposing version `v2` a separate branch `v1` would be a good idea in case of changes.
My focus is now `v2`...

**Comment by dasrick** [comment]
> For my own CI runs (using GitHub Actions Workflows), I am using both golint and golangci-lint, but at this point it is probably overkill. I originally enabled both to see if golint happened to catch any issues that golangci-lint did not, but I've not seen anything from golint that golangci-lint didn't catch.

`golangci-lint` combine a lot of tool and provide the possibility to enable and configure this tools. so `golint` is part of this toolbox. when you take a look into a "bigger" golangci-lint configuration then you will get a better idea what happens inside.
